name: lint

on:
  push:
    branches: [ test ]

jobs:
  lint-tgt:
    name: SystemVerilog Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chipsalliance/verible-linter-action@main
        with:
          paths: |
            ./rtl
          # extra_args: "--waiver_files lint/common_cells.style.waiver --rules=-interface-name-style --lint_fatal"
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # reviewdog_reporter: github-check
